import Logo from "@/app/(DashboardLayout)/layout/shared/logo/FullLogo";
import CardBox from "@/app/components/shared/CardBox";
import React from "react";
import Link from "next/link";
import type { Metadata } from "next";
import BoxedAuthLogin from "../../authforms/BoxedAuthForms";
import BoxedAuthSlider from "../../authforms/BoxedAuthSlider";
export const metadata: Metadata = {
  title: "تسجيل الدخول",
  description: "Generated by create next app",
};
const BoxedLogin = () => {
  return (
    <>
      <div className="relative min-h-screen flex flex-col justify-center bg-cover bg-center bg-[url('/images/backgrounds/login-bg.jpg')]" dir="rtl">
        <div className="flex h-full justify-center items-center px-4">
          <CardBox className="xl:max-w-6xl lg:max-w-3xl md:max-w-xl w-full border-none p-0">
            <div className="grid grid-cols-12">
              <div className="xl:col-span-6 col-span-12 px-8 xl:border-e border-ld">
                <div className="md:py-14 py-8 lg:px-6">
                  <Logo />
                  <h3 className="md:text-34 text-2xl md:my-8 my-5">دعنا نساعدك في تسجيل الدخول</h3>
                  <BoxedAuthLogin />
                </div>
              </div>
              <div className="xl:col-span-6 col-span-12 xl:block hidden">
                <BoxedAuthSlider />
              </div>
            </div>
          </CardBox>
        </div>
      </div>
    </>
  );
};

export default BoxedLogin;
